/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CashfreeOrder = IDL.Record({
  'order_id' : IDL.Text,
  'payment_session_id' : IDL.Text,
});
export const Payment = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Nat,
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCashfreeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [CashfreeOrder],
      [],
    ),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
  'getSortedPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'handleCashfreeWebhook' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CashfreeOrder = IDL.Record({
    'order_id' : IDL.Text,
    'payment_session_id' : IDL.Text,
  });
  const Payment = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Nat,
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCashfreeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [CashfreeOrder],
        [],
      ),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Text], [IDL.Opt(Payment)], ['query']),
    'getSortedPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'handleCashfreeWebhook' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };